import { useEffect, useRef, useState, type ReactNode } from "react";
import { X } from "lucide-react";
import { instant, safeURL, uid, type BookFlight, type BookRental, type BookTicket, type Handbook } from "./model";

export function Modal({ title, children, onClose }: { title: string; children: ReactNode; onClose: () => void }) {
  const ref = useRef<HTMLDialogElement>(null);
  useEffect(() => { const d = ref.current!; d.showModal(); return () => d.close(); }, []);
  return <dialog ref={ref} className="hb-dialog" onCancel={e => { e.preventDefault(); onClose(); }} onClick={e => { if (e.target === e.currentTarget) onClose(); }}><div className="hb-dialog-inner"><header className="hb-row"><h2>{title}</h2><button type="button" className="hb-icon" onClick={onClose} aria-label="关闭弹窗"><X size={20}/></button></header>{children}</div></dialog>;
}
export function Field({ label, name, value = "", type = "text", required = false }: { label: string; name: string; value?: string; type?: string; required?: boolean }) {
  return <label className="hb-field">{label}<input name={name} defaultValue={value} type={type} required={required} maxLength={1000}/></label>;
}
export function Area({ label, name, value = "" }: { label: string; name: string; value?: string }) { return <label className="hb-field">{label}<textarea name={name} defaultValue={value} rows={3} maxLength={12000}/></label>; }
function Form({ children, onSubmit }: { children: ReactNode; onSubmit: (form: FormData) => Promise<void> }) {
  const [error, setError] = useState(""), [saving, setSaving] = useState(false);
  return <form className="hb-form" onSubmit={e => { e.preventDefault(); const data = new FormData(e.currentTarget); setSaving(true); setError(""); void onSubmit(data).catch(e => setError(e.message || "没有保存成功，请重试。")).finally(() => setSaving(false)); }}><fieldset disabled={saving}>{children}</fieldset>{error && <p className="hb-error" role="alert">{error}</p>}<button className="hb-primary" disabled={saving}>{saving ? "正在保存…" : "保存到手册"}</button></form>;
}
const val = (f: FormData, key: string) => String(f.get(key) || "").trim();
const lines = (f: FormData, key: string) => val(f, key).split("\n").map(s => s.trim()).filter(Boolean);
const url = (f: FormData, key: string) => { const raw = val(f, key); if (raw && !safeURL(raw)) throw new Error("链接须以 https:// 或 http:// 开头。"); return safeURL(raw); };
function validateTimes(a: string, ao: string, b: string, bo: string) {
  const dep = instant(a, ao), arr = instant(b, bo);
  if ((a && dep == null) || (b && arr == null)) throw new Error("请填写有效的日期、时间和 UTC 时差（如 +08:00）。");
  if (dep != null && arr != null && arr <= dep) throw new Error("结束时间必须晚于出发时间，请同时核对当地时区。");
}
export function FlightEditor({ initial, onSave, onClose }: { initial?: BookFlight; onSave: (f: BookFlight) => Promise<void>; onClose: () => void }) {
  return <Modal title={initial ? "编辑这一程" : "添加航班 / 车次"} onClose={onClose}><Form onSubmit={async f => { validateTimes(val(f, "departure"), val(f, "departureOffset"), val(f, "arrival"), val(f, "arrivalOffset")); await onSave({ ...initial, id: initial?.id || `manual-${uid()}`, title: val(f, "title"), number: val(f, "number"), from: val(f, "from"), to: val(f, "to"), departure: val(f, "departure"), arrival: val(f, "arrival"), departureOffset: val(f, "departureOffset"), arrivalOffset: val(f, "arrivalOffset"), note: val(f, "note"), url: url(f, "url") }); onClose(); }}>
    <div className="hb-grid"><Field name="title" label="这一程的名字" value={initial?.title} required/><Field name="number" label="航班号 / 车次" value={initial?.number}/><Field name="from" label="出发机场 / 车站" value={initial?.from} required/><Field name="to" label="抵达机场 / 车站" value={initial?.to} required/><Field name="departure" label="当地出发时间" type="datetime-local" value={initial?.departure}/><Field name="departureOffset" label="出发地 UTC 时差" value={initial?.departureOffset || "+08:00"}/><Field name="arrival" label="当地抵达时间" type="datetime-local" value={initial?.arrival}/><Field name="arrivalOffset" label="抵达地 UTC 时差" value={initial?.arrivalOffset || "+08:00"}/></div><p className="hb-muted">时间可稍后补充。跨时区旅行请填写出行当天的时差（含夏令时）；倒计时按实际时差计算，不代表实时航班动态。</p><Field name="url" label="查询 / 预订链接" value={initial?.url} type="url"/><Area name="note" label="行李、转机与其他提醒" value={initial?.note}/>
  </Form></Modal>;
}
export function TicketEditor({ initial, book, onSave, onClose }: { initial?: BookTicket; book: Handbook; onSave: (t: BookTicket) => Promise<void>; onClose: () => void }) {
  return <Modal title={initial ? "编辑票券" : "添加门票 / 预订"} onClose={onClose}><Form onSubmit={async f => { await onSave({ ...initial, id: initial?.id || uid(), title: val(f, "title"), dayId: val(f, "dayId"), purchased: initial?.purchased || false, note: val(f, "note"), url: url(f, "url") }); onClose(); }}><Field name="title" label="票券名称" value={initial?.title} required/><label className="hb-field">安排在哪一天<select name="dayId" defaultValue={initial?.dayId || ""}><option value="">尚未安排</option>{book.days.map((d, i) => <option key={d.id} value={d.id}>第 {i + 1} 天 · {d.title}</option>)}</select></label><Field name="url" label="购买 / 预约入口" value={initial?.url} type="url"/><Area name="note" label="时段、价格与使用提醒" value={initial?.note}/></Form></Modal>;
}
export function RentalEditor({ initial, onSave, onClose }: { initial?: BookRental; onSave: (r: BookRental) => Promise<void>; onClose: () => void }) {
  return <Modal title={initial ? "编辑租车安排" : "添加租车安排"} onClose={onClose}><Form onSubmit={async f => { validateTimes(val(f, "pickup"), val(f, "pickupOffset"), val(f, "dropoff"), val(f, "dropoffOffset")); const links = lines(f, "links").map(line => { const [title, ...parts] = line.split("|"); const address = parts.length ? parts.join("|").trim() : title; if (!safeURL(address)) throw new Error("参考链接请填写 名称 | https://…，每行一个。"); return { title: parts.length ? title.trim() : "参考资料", url: safeURL(address)! }; }); await onSave({ id: initial?.id || uid(), company: val(f, "company"), vehicle: val(f, "vehicle"), pickup: val(f, "pickup"), dropoff: val(f, "dropoff"), pickupOffset: val(f, "pickupOffset"), dropoffOffset: val(f, "dropoffOffset"), pickupPlace: val(f, "pickupPlace"), returnPlace: val(f, "returnPlace"), price: val(f, "price"), contact: val(f, "contact"), checklist: lines(f, "checklist"), insurance: lines(f, "insurance"), driving: lines(f, "driving"), links, returned: initial?.returned || false }); onClose(); }}><div className="hb-grid"><Field name="company" label="租车公司" value={initial?.company} required/><Field name="vehicle" label="车型 / 车牌" value={initial?.vehicle}/><Field name="pickup" type="datetime-local" label="当地取车时间" value={initial?.pickup}/><Field name="pickupOffset" label="取车地 UTC 时差" value={initial?.pickupOffset || "+08:00"}/><Field name="dropoff" type="datetime-local" label="当地还车截止时间" value={initial?.dropoff}/><Field name="dropoffOffset" label="还车地 UTC 时差" value={initial?.dropoffOffset || "+08:00"}/><Field name="pickupPlace" label="取车点" value={initial?.pickupPlace}/><Field name="returnPlace" label="还车点与到达建议" value={initial?.returnPlace}/><Field name="price" label="费用与币种（以订单为准）" value={initial?.price}/><Field name="contact" label="联系 / 救援电话" value={initial?.contact}/></div><Area name="checklist" label="取还车检查项 · 每行一项" value={initial?.checklist.join("\n") || "拍摄车身与油表\n核对保险与押金\n保存还车凭证"}/><Area name="insurance" label="保险与理赔提示 · 每行一项" value={initial?.insurance.join("\n")}/><Area name="driving" label="当地驾驶提醒 · 每行一项" value={initial?.driving.join("\n")}/><Area name="links" label="参考链接 · 名称 | https://…，每行一个" value={initial?.links.map(l => `${l.title} | ${l.url}`).join("\n")}/></Form></Modal>;
}
export function DayEditor({ book, dayID, onSave, onClose }: { book: Handbook; dayID?: string; onSave: (days: Handbook["days"]) => Promise<void>; onClose: () => void }) {
  const day = book.days.find(d => d.id === dayID);
  return <Modal title={day ? "编辑每日行程" : "添加一天"} onClose={onClose}><Form onSubmit={async f => { const items = lines(f, "items").map((line, i) => { const [time, title, ...note] = line.split("|").map(t => t.trim()); if (!title) throw new Error("行程按 时间 | 地点或安排 | 提醒 填写，每行一站。"); const old = day?.items[i]; return { id: old?.id || uid(), time, title, note: note.join(" | "), placeIds: old?.title === title ? old.placeIds : book.places.filter(p => p.name === title).map(p => p.id), ticketIds: old?.title === title ? old.ticketIds : [] }; }); const next = { id: day?.id || uid(), date: val(f, "date"), title: val(f, "title"), notes: lines(f, "notes"), items }; await onSave(day ? book.days.map(d => d.id === day.id ? next : d) : [...book.days, next]); onClose(); }}><Field label="这一天的名字" name="title" value={day?.title} required/><Field label="日期" name="date" value={day?.date} type="date"/><Area label="逐站安排 · 时间 | 地点或安排 | 提醒" name="items" value={day?.items.map(i => `${i.time} | ${i.title} | ${i.note}`).join("\n")}/><Area label="日程说明与费用参考 · 每行一条" name="notes" value={day?.notes.join("\n")}/><p className="hb-muted">这里只编辑随行手册，不改写主地图中的规划。未匹配已有地点的文字安排不会生成虚构坐标。</p></Form></Modal>;
}
export function BookSettings({ book, onSave, onClose }: { book: Handbook; onSave: (patch: Partial<Handbook>) => Promise<void>; onClose: () => void }) {
  return <Modal title="手册信息与模块" onClose={onClose}><Form onSubmit={async f => { const timeZone = val(f, "timeZone"); try { new Intl.DateTimeFormat("zh", { timeZone }).format(); } catch { throw new Error("请填写有效时区，如 Asia/Shanghai 或 Europe/Paris。"); } const modules = Object.fromEntries(Object.keys(book.modules).map(m => [m, f.has(m)])) as Handbook["modules"]; modules.overview = true; await onSave({ title: val(f, "title"), timeZone, notes: lines(f, "notes"), modules }); onClose(); }}><Field label="旅程标题" name="title" value={book.title} required/><Field label="行程时区（用于‘今天’）" name="timeZone" value={book.timeZone} required/><div className="hb-grid">{Object.entries(book.modules).filter(([m]) => m !== "overview").map(([m, checked]) => <label className="hb-check" key={m}><input type="checkbox" name={m} defaultChecked={checked}/>{{ flights: "航班交通", route: "路线地图", itinerary: "每日行程", tickets: "票券夹", driving: "租车自驾", todo: "出发清单", ledger: "同行账本" }[m]}</label>)}</div><Area name="notes" label="旅行提醒 · 每行一条" value={book.notes.join("\n")}/><p className="hb-muted">隐藏模块不会删除其中的数据。</p></Form></Modal>;
}
