import { lazy, Suspense, useCallback, useEffect, useRef, useState, type ReactNode } from "react";
import { ArrowLeft, ArrowRight, BookOpen, CalendarDays, CarFront, Check, CheckCheck, ChevronLeft, ChevronRight, Download, ExternalLink, FileText, ListChecks, Map, Pencil, Plane, Plus, Printer, RefreshCw, Settings2, Share2, Ticket, Trash2, Upload, Wallet, X } from "lucide-react";
import { useApp } from "../store";
import { MODULES, MODULE_TITLES, emptyHandbook, flightStatus, countdown, instant, fromPlanner, importTravelPage, ledgerCSV, todayIn, uid, validateLedger, type BookDocument, type BookFlight, type BookPlace, type BookRental, type BookTicket, type Handbook, type Module } from "./model";
import { backup, deleteBook, download, listBooks, readDocument, saveBook } from "./storage";
import { BookSettings, DayEditor, FlightEditor, Modal, RentalEditor, TicketEditor } from "./Editors";
import LedgerFrame from "./LedgerFrame";
import SyncPanel from "./SyncPanel";
import "./handbook.css";

const HandbookMap = lazy(() => import("./HandbookMap"));
const icons = { overview: BookOpen, flights: Plane, route: Map, itinerary: CalendarDays, tickets: Ticket, driving: CarFront, todo: ListChecks, ledger: Wallet };
type Edit = { kind: "flight"; item?: BookFlight } | { kind: "ticket"; item?: BookTicket } | { kind: "rental"; item?: BookRental } | { kind: "day"; id?: string } | { kind: "settings" };
const errText = (e: unknown) => e instanceof Error ? e.message : "操作没有完成，请重试。";
export default function HandbookPanel({ dark, onClose }: { dark: boolean; onClose: () => void }) {
  const app = useApp(), [book, setBook] = useState<Handbook>(), [books, setBooks] = useState<Handbook[]>([]), [tab, setTab] = useState<Module>("overview"), [error, setError] = useState(""), [saving, setSaving] = useState(false), [notice, setNotice] = useState(""), [edit, setEdit] = useState<Edit>(), [preview, setPreview] = useState<BookDocument>(), [share, setShare] = useState(false), [ledgerVisited, setLedgerVisited] = useState(false), [openDay, setOpenDay] = useState(""), [todoText, setTodoText] = useState("");
  const ref = useRef<HTMLDialogElement>(null), current = useRef<Handbook>(), queue = useRef(Promise.resolve()), count = useRef(0), file = useRef<HTMLInputElement>(null), content = useRef<HTMLDivElement>(null), mounted = useRef(true);
  useEffect(() => { const d = ref.current!; d.showModal(); mounted.current = true; return () => { mounted.current = false; d.close(); }; }, []);
  const select = useCallback((b: Handbook) => { current.current = b; setBook(b); setLedgerVisited(false); setOpenDay(b.days.find(d => d.date === todayIn(b.timeZone))?.id || b.days.find(d => d.items.length)?.id || ""); setTab("overview"); setNotice(""); try { localStorage.setItem("anytravel-handbook-active", b.id); } catch { /* IndexedDB remains the authoritative saved copy. */ } }, []);
  const load = useCallback(async () => {
    try { const stored = await listBooks(); if (!mounted.current) return; setBooks(stored); const existing = stored.find(b => b.id === app.state.currentTripID); const recent = stored.find(b => b.id === localStorage.getItem("anytravel-handbook-active")); const initial = app.state.plan ? existing || fromPlanner(app.state) : recent || stored[0] || fromPlanner(app.state); if (!stored.some(b => b.id === initial.id)) { await saveBook(initial); setBooks([initial, ...stored]); } if (mounted.current) select(initial); }
    catch (e) { setError(errText(e)); }
  }, []);
  useEffect(() => { void load(); }, [load]);
  const commit = useCallback((mutate: (b: Handbook) => Handbook): Promise<void> => {
    count.current++; setSaving(true);
    const task = queue.current.then(async () => {
      if (!current.current) throw new Error("手册尚未载入。");
      const next = { ...mutate(structuredClone(current.current)), updatedAt: new Date().toISOString() };
      await saveBook(next); current.current = next;
      if (mounted.current) { setBook(next); setBooks(old => [next, ...old.filter(b => b.id !== next.id)]); setError(""); }
    });
    queue.current = task.catch(e => { if (mounted.current) setError(errText(e)); }).finally(() => { count.current--; if (mounted.current) setSaving(count.current > 0); });
    return task;
  }, []);
  const run = (p: Promise<unknown>) => { void p.catch(e => setError(errText(e))); };
  const changeTab = (m: Module) => { setTab(m); if (m === "ledger") setLedgerVisited(true); history.pushState({ handbook: m }, "", `#handbook=${m}`); content.current?.scrollTo({ top: 0, behavior: "instant" }); };
  useEffect(() => {
    const navigate = () => { const m = new URLSearchParams(location.hash.slice(1)).get("handbook") as Module; if (MODULES.includes(m) && current.current?.modules[m]) { setTab(m); if (m === "ledger") setLedgerVisited(true); } };
    window.addEventListener("popstate", navigate); navigate(); return () => window.removeEventListener("popstate", navigate);
  }, [book?.id]);
  const close = () => { if (count.current) { setNotice("正在保存，请稍候再返回地图。"); return; } if (location.hash.startsWith("#handbook=")) history.replaceState(null, "", location.pathname + location.search); onClose(); };
  const locate = (p: BookPlace) => { if (!p.coordinate) { setNotice("这处地点还没有坐标，可从路线页打开外部地图搜索。"); return; } app.setFocus({ kind: "place", id: p.id, coordinate: p.coordinate }); close(); };
  const addAttachment = async (id: string, file: File) => { const doc = await readDocument(file); await commit(b => ({ ...b, documents: [...b.documents.filter(d => d.id !== b.tickets.find(t => t.id === id)?.documentId), doc], tickets: b.tickets.map(t => t.id === id ? { ...t, documentId: doc.id } : t) })); setNotice("票据已保存在这台设备；导出备份时会一起带走。"); };
  const remove = (collection: "flights" | "tickets" | "rentals" | "todos" | "days", id: string) => { if (!confirm("从这本手册移除？主地图规划不会改变。")) return; run(commit(b => { const next = { ...b, [collection]: b[collection].filter(row => row.id !== id) }; if (collection === "tickets") next.documents = next.documents.filter(d => next.tickets.some(t => t.documentId === d.id)); return next; })); };
  const importFile = async (file: File) => {
    if (file.size > 34 * 1024 * 1024) throw new Error("备份文件超过 34 MB。");
    const incoming = importTravelPage(JSON.parse(await file.text()));
    // Always import a separate copy so an old backup never silently overwrites current bills.
    incoming.id = uid(); incoming.updatedAt = new Date().toISOString();
    await saveBook(incoming); setBooks(old => [incoming, ...old]); select(incoming); setNotice("已导入为独立手册，没有覆盖原行程或账本。");
  };
  const upsert = <T extends { id: string },>(rows: T[], row: T) => rows.some(r => r.id === row.id) ? rows.map(r => r.id === row.id ? row : r) : [...rows, row];
  const printBook = () => { document.body.classList.add("printing-handbook"); window.print(); document.body.classList.remove("printing-handbook"); };
  return <dialog ref={ref} className={`hb-shell${dark ? " dark" : ""}`} aria-label="随行手册" onCancel={e => { e.preventDefault(); close(); }}>
    <header className="hb-top"><button className="hb-back" onClick={close}><ArrowLeft size={20}/><span>回到地图</span></button><div className="hb-brand"><BookOpen size={20}/><span>折叠远方 <small>随行手册</small></span></div><span className="hb-save-state" role="status">{saving ? "保存中…" : book ? "已存本机" : "读取中…"}</span></header>
    {!book ? <div className="hb-empty"><BookOpen/><h2>{error ? "手册暂时没有打开" : "正在翻开旅程…"}</h2><p role="alert">{error}</p>{error && <button className="hb-primary" onClick={() => { setError(""); void load(); }}>重试读取</button>}</div> : <>
      <nav className="hb-nav" aria-label="手册章节">{MODULES.filter(m => book.modules[m]).map(m => { const Icon = icons[m]; return <button key={m} aria-current={tab === m ? "page" : undefined} onClick={() => changeTab(m)}><Icon size={19}/><span>{MODULE_TITLES[m]}</span></button>; })}</nav>
      <div className="hb-content" ref={content}>
        <div className="hb-page-heading"><div><span className="hb-eyebrow">{MODULE_TITLES[tab]} / {book.days.length || "—"} DAYS</span><h1>{book.title}</h1></div><button className="hb-icon" onClick={() => setEdit({ kind: "settings" })} aria-label="手册信息与模块"><Settings2 size={20}/></button></div>
        {error && <div className="hb-error" role="alert">{error}<button onClick={() => setError("")} aria-label="关闭错误提示"><X size={18}/></button></div>}{notice && <div className="hb-notice" role="status">{notice}<button onClick={() => setNotice("")} aria-label="关闭提示"><X size={18}/></button></div>}
        {tab === "overview" && <>
          <div className="hb-hero"><span className="hb-eyebrow">把琐碎安放好，把时间留给远方</span><h2>行前有准备，<br/>途中有着落。</h2><p>路线、预订、票据与同行账目，收在同一本手册里。</p><div className="hb-row"><span>{book.days[0]?.date || "出发日期待定"}{book.days.length > 1 ? ` — ${book.days.at(-1)?.date || "返程待定"}` : ""}</span><span>{book.timeZone}</span></div></div>
          <div className="hb-stats">{[["itinerary", `${book.days.length}`, "每日安排"], ["tickets", `${book.tickets.filter(t => t.purchased).length}/${book.tickets.length}`, "票券已确认"], ["todo", `${book.todos.filter(t => t.completed).length}/${book.todos.length}`, "行前已准备"], ["ledger", (book.ledger.bills.reduce((n, b) => n + b.baseAmountCents, 0) / 100).toFixed(2), `${book.ledger.settings.baseCurrency} 已记支出`]].map(([m, value, label]) => <button key={m} disabled={!book.modules[m as Module]} onClick={() => changeTab(m as Module)}><strong>{value}</strong><span>{label}</span></button>)}</div>
          <section className="hb-card"><div className="hb-section-heading"><h2>这本手册</h2><label className="hb-select-book">切换旅册<select disabled={saving} value={book.id} onChange={e => { const b = books.find(b => b.id === e.target.value); if (b) select(b); }}>{books.map(b => <option value={b.id} key={b.id}>{b.title}</option>)}</select></label></div><div className="hb-actions"><button disabled={saving || !app.state.plan} onClick={() => { if (book.id !== app.state.currentTripID) { setNotice("这是独立手册，请点‘收下当前行程’创建主地图对应的手册。"); return; } if (confirm("从主地图更新每日路线、住宿和交通？票据、待办、账本与手工添加的航班会保留。")) run(commit(b => fromPlanner(app.state, b))); }}><RefreshCw size={16}/>更新当前路线</button><button disabled={saving} onClick={() => run((async () => { const existing = books.find(b => b.id === app.state.currentTripID); const b = existing || fromPlanner(app.state); await saveBook(b); setBooks(old => [b, ...old.filter(p => p.id !== b.id)]); select(b); })())}><Plus size={16}/>收下当前行程</button><button disabled={saving} onClick={() => run((async () => { const b = emptyHandbook(); await saveBook(b); setBooks(old => [b, ...old]); select(b); setEdit({ kind: "settings" }); })())}><BookOpen size={16}/>空白手册</button></div><p className="hb-muted">规划与手册各自保存，点击更新才会带入新的路线。当前仅存这台设备，清理网站数据会移除手册，请定期备份。</p><div className="hb-actions"><button onClick={() => backup(book)}><Download size={16}/>导出完整备份</button><button disabled={saving} onClick={() => file.current?.click()}><Upload size={16}/>导入旅行资料</button><button onClick={printBook}><Printer size={16}/>打印 / 存为 PDF</button><button onClick={() => setShare(true)}><Share2 size={16}/>多设备同步</button></div><input hidden ref={file} type="file" accept=".json,application/json" onChange={e => { const f = e.target.files?.[0]; if (f) run(importFile(f)); e.target.value = ""; }}/><p className="hb-muted">支持 Travel-Plan-Page 的两种 JSON 格式与本应用备份；PDF、图片需在票券夹添加。备份包含票据和账目，请仅分享给可信的同行人。</p></section>
          {book.stays.length > 0 && <section className="hb-card"><h2>今晚的落脚处</h2>{book.stays.map(s => <article className="hb-stay" key={s.id}><h3>{s.title}</h3><p>{s.address}</p><p>{s.note}</p>{s.url && <External href={s.url}>查看住宿</External>}</article>)}</section>}
          {book.notes.length > 0 && <section className="hb-card"><h2>随身提醒</h2><ul>{book.notes.map((n, i) => <li key={i}>{n}</li>)}</ul></section>}
          <footer className="hb-overview-footer"><p>手册功能整合自 <External href="https://github.com/do-tongxue/Travel-Plan-Page">Travel-Plan-Page</External> · MIT 开源许可</p><button className="hb-danger" disabled={saving} onClick={() => { if (confirm("永久删除这本本地手册和附件？建议先导出备份。")) run((async () => { await deleteBook(book.id); const rest = books.filter(b => b.id !== book.id); if (rest.length) { setBooks(rest); select(rest[0]); } else { const b = emptyHandbook(); await saveBook(b); setBooks([b]); select(b); } })()); }}><Trash2 size={16}/>删除这本手册</button></footer>
        </>}
        {tab === "flights" && <><Section title="每一程，都心中有数" action={<button onClick={() => setEdit({ kind: "flight" })}><Plus size={18}/>添加航班 / 车次</button>}/><FlightCarousel flights={book.flights} edit={f => setEdit({ kind: "flight", item: f })} remove={id => remove("flights", id)}/><p className="hb-muted">倒计时使用你保存的计划时刻，不代表航司或铁路实时运行状态；请以承运方通知为准。</p></>}
        {tab === "route" && <Suspense fallback={<div className="hb-empty">地图正在展开…</div>}><HandbookMap book={book} dark={dark} onLocate={locate}/></Suspense>}
        {tab === "itinerary" && <><Section title="把每一天慢慢展开" action={<button onClick={() => setEdit({ kind: "day" })}><Plus size={18}/>添加一天</button>}/>{!book.days.length && <Empty icon={<CalendarDays/>}>可以从主地图收下规划，也可以自己添加每一天。</Empty>}{book.days.map((d, i) => <section className="hb-day" key={d.id}><button className="hb-day-heading" aria-expanded={openDay === d.id} onClick={() => setOpenDay(openDay === d.id ? "" : d.id)}><span className="hb-index">{String(i + 1).padStart(2, "0")}</span><span><small>{d.date || "日期待定"}{d.date === todayIn(book.timeZone) && <b className="hb-today">今天</b>}</small><strong>{d.title}</strong></span><ChevronRight className={openDay === d.id ? "hb-rotate" : ""} size={18}/></button>{openDay === d.id && <div className="hb-day-body"><div className="hb-actions"><button onClick={() => setEdit({ kind: "day", id: d.id })}><Pencil size={15}/>编辑</button><button onClick={() => remove("days", d.id)}><Trash2 size={15}/>移除</button></div><ol className="hb-timeline">{d.items.map((item, j) => <li key={item.id}><span className="hb-timeline-dot">{j + 1}</span><div><time>{item.time || "时间留白"}</time><h3>{item.title}</h3>{item.note && <p>{item.note}</p>}<div className="hb-actions">{item.placeIds.map(id => book.places.find(p => p.id === id)).filter((p): p is BookPlace => !!p).map(p => <button key={p.id} onClick={() => locate(p)}><Map size={14}/>{p.name}</button>)}</div>{book.tickets.filter(t => item.ticketIds.includes(t.id) || (t.placeId && item.placeIds.includes(t.placeId))).map(t => <button key={t.id} className="hb-ticket-badge" onClick={() => changeTab("tickets")} disabled={!book.modules.tickets}><Ticket size={14}/>{t.title} · {t.purchased ? "已确认" : "待预订"}<ArrowRight size={14}/></button>)}</div></li>)}</ol>{d.notes.length > 0 && <ul className="hb-day-notes">{d.notes.map((n, j) => <li key={j}>{n}</li>)}</ul>}</div>}</section>)}</>}
        {tab === "tickets" && <><Section title="把票据装进口袋" action={<button onClick={() => setEdit({ kind: "ticket" })}><Plus size={18}/>添加票券</button>}/>{!book.tickets.length && <Empty icon={<Ticket/>}>门票、车票与预约凭证，都可以保存在这里。</Empty>}<div className="hb-grid">{[...book.tickets].sort((a, b) => Number(a.purchased) - Number(b.purchased)).map(t => { const doc = book.documents.find(d => d.id === t.documentId); return <article key={t.id} className={`hb-card hb-ticket${t.purchased ? " is-done" : ""}`}><div className="hb-section-heading"><span className="hb-tag">{t.purchased ? "已确认" : "待预订"}</span><div className="hb-actions"><button className="hb-icon" aria-label={`编辑${t.title}`} onClick={() => setEdit({ kind: "ticket", item: t })}><Pencil size={16}/></button><button className="hb-icon" aria-label={`删除${t.title}`} onClick={() => remove("tickets", t.id)}><Trash2 size={16}/></button></div></div><h3>{t.title}</h3><small>{book.days.find(d => d.id === t.dayId)?.title || "未安排日期"}</small><p>{t.note}</p><div className="hb-actions">{t.url && <External href={t.url}>购买 / 预约</External>}{t.documentURL && <External href={t.documentURL}>原始电子票</External>}{doc && <button onClick={() => setPreview(doc)}><FileText size={16}/>查看票据</button>}<label className="hb-file-button"><Upload size={16}/>{doc ? "更换附件" : "添加 PDF / 图片"}<input type="file" accept="application/pdf,image/png,image/jpeg,image/webp" disabled={saving} onChange={e => { const f = e.target.files?.[0]; if (f) run(addAttachment(t.id, f)); e.target.value = ""; }}/></label></div><button className={t.purchased ? "hb-secondary" : "hb-primary"} disabled={saving} onClick={() => run(commit(b => ({ ...b, tickets: b.tickets.map(row => row.id === t.id ? { ...row, purchased: !row.purchased } : row) })))}>{t.purchased ? <CheckCheck size={17}/> : <Check size={17}/>} {t.purchased ? "取消已确认状态" : "标记已购买 / 已预约"}</button></article>; })}</div></>}
        {tab === "driving" && <><Section title="方向盘之外，也有准备" action={<button onClick={() => setEdit({ kind: "rental" })}><Plus size={18}/>添加租车</button>}/>{!book.rentals.length && <Empty icon={<CarFront/>}>记录取还车时间、保险、车况检查与当地驾驶提醒。</Empty>}{book.rentals.map(r => <Rental key={r.id} rental={r} edit={() => setEdit({ kind: "rental", item: r })} remove={() => remove("rentals", r.id)} returned={() => run(commit(b => ({ ...b, rentals: b.rentals.map(p => p.id === r.id ? { ...p, returned: !p.returned } : p) })))}/>)}</>}
        {tab === "todo" && <><Section title="出发前，少一点挂念"/><div className="hb-card"><div className="hb-section-heading"><h3>{book.todos.filter(t => t.completed).length} / {book.todos.length} 已准备好</h3><span className="hb-tag">行前清单</span></div><progress value={book.todos.filter(t => t.completed).length} max={Math.max(1, book.todos.length)}/><form className="hb-row hb-todo-form" onSubmit={e => { e.preventDefault(); if (todoText.trim()) run(commit(b => ({ ...b, todos: [...b.todos, { id: uid(), text: todoText.trim(), completed: false }] })).then(() => setTodoText(""))); }}><input aria-label="添加待办事项" placeholder="例如：确认预约，带好证件…" value={todoText} onChange={e => setTodoText(e.target.value)} maxLength={200}/><button className="hb-primary" disabled={saving || !todoText.trim()}><Plus size={17}/>添加</button></form>{!book.todos.length && <p className="hb-empty">还没有待办，写下第一件需要准备的事。</p>}{book.todos.map(t => <div key={t.id} className="hb-todo"><label><input type="checkbox" checked={t.completed} disabled={saving} onChange={() => run(commit(b => ({ ...b, todos: b.todos.map(row => row.id === t.id ? { ...row, completed: !row.completed } : row) })))} /><span className={t.completed ? "hb-done" : ""}>{t.text}</span></label><button className="hb-icon" aria-label={`删除待办${t.text}`} onClick={() => remove("todos", t.id)}><Trash2 size={16}/></button></div>)}</div></>}
        {(ledgerVisited || tab === "ledger") && <div hidden={tab !== "ledger"}><Section title="每笔花费，都算得清楚" action={<button onClick={() => download(ledgerCSV(book.ledger), `${book.title}-同行账本.csv`, "text/csv;charset=utf-8")}><Download size={16}/>导出账单 CSV</button>}/><p className="hb-muted">用实际支付的结算币金额记账，不会自动套用未经确认的汇率。最多 12 位同行人；所有账目均保存在这本手册中。</p><LedgerFrame key={book.id} book={book} dark={dark} onSave={snapshot => commit(b => ({ ...b, ledger: validateLedger(snapshot) }))}/></div>}
      </div>
      <div className="hb-print"><h1>{book.title}</h1><p>{book.timeZone} · {book.updatedAt.slice(0, 10)} 导出</p>{book.flights.map(f => <section key={f.id}><h2>{f.title} {f.number}</h2><p>{f.from} {f.departure} UTC{f.departureOffset} → {f.to} {f.arrival} UTC{f.arrivalOffset}</p><p>{f.note}</p></section>)}{book.days.map(d => <section key={d.id}><h2>{d.date} · {d.title}</h2>{d.items.map(i => <p key={i.id}><strong>{i.time} {i.title}</strong><br/>{i.note}</p>)}{d.notes.map((n, i) => <p key={i}>{n}</p>)}</section>)}<h2>住宿与票券</h2>{book.stays.map(s => <p key={s.id}>{s.title} · {s.address} · {s.note}</p>)}{book.tickets.map(t => <p key={t.id}>{t.purchased ? "[已确认]" : "[待预订]"} {t.title} · {t.note}</p>)}{book.rentals.map(r => <section key={r.id}><h2>租车 · {r.company}</h2><p>取车 {r.pickup} {r.pickupPlace}<br/>还车 {r.dropoff} {r.returnPlace}<br/>{r.price} {r.contact}</p>{[...r.checklist, ...r.insurance, ...r.driving].map((s, i) => <p key={i}>{s}</p>)}</section>)}<h2>行前清单</h2>{book.todos.map(t => <p key={t.id}>{t.completed ? "☑" : "□"} {t.text}</p>)}<h2>已记账支出 · {book.ledger.settings.baseCurrency}</h2>{book.ledger.bills.map(b => <p key={b.id}>{b.orderedAt} · {b.category} · {b.note} · {(b.baseAmountCents / 100).toFixed(2)}</p>)}<strong>合计 {(book.ledger.bills.reduce((sum, b) => sum + b.baseAmountCents, 0) / 100).toFixed(2)}</strong></div>
      {edit?.kind === "settings" && <BookSettings book={book} onClose={() => setEdit(undefined)} onSave={patch => commit(b => ({ ...b, ...patch }))}/>}
      {edit?.kind === "flight" && <FlightEditor initial={edit.item} onClose={() => setEdit(undefined)} onSave={f => commit(b => ({ ...b, flights: upsert(b.flights, f) }))}/>}
      {edit?.kind === "ticket" && <TicketEditor initial={edit.item} book={book} onClose={() => setEdit(undefined)} onSave={t => commit(b => ({ ...b, tickets: upsert(b.tickets, t) }))}/>}
      {edit?.kind === "rental" && <RentalEditor initial={edit.item} onClose={() => setEdit(undefined)} onSave={r => commit(b => ({ ...b, rentals: upsert(b.rentals, r) }))}/>}
      {edit?.kind === "day" && <DayEditor book={book} dayID={edit.id} onClose={() => setEdit(undefined)} onSave={days => commit(b => ({ ...b, days }))}/>}
      {preview && <DocumentPreview doc={preview} onClose={() => setPreview(undefined)}/>}
      {share && <SyncPanel book={book} backendURL={app.state.settings.backendURL} onClose={() => setShare(false)} onImport={async incoming => { incoming.id = book.id; await commit(() => incoming); setLedgerVisited(false); }}/>}
    </>}
  </dialog>;
}
function Section({ title, action }: { title: string; action?: ReactNode }) { return <div className="hb-section-heading"><h2>{title}</h2>{action && <div className="hb-actions">{action}</div>}</div>; }
function Empty({ children, icon }: { children: ReactNode; icon: ReactNode }) { return <div className="hb-empty">{icon}<p>{children}</p></div>; }
function External({ href, children }: { href: string; children: ReactNode }) { return <a href={href} target="_blank" rel="noopener noreferrer">{children}<ExternalLink size={14}/></a>; }
function useClock() { const [now, setNow] = useState(Date.now()); useEffect(() => { const id = setInterval(() => { if (!document.hidden) setNow(Date.now()); }, 1000); return () => clearInterval(id); }, []); return now; }
function FlightClock({ flight }: { flight: BookFlight }) { const now = useClock(), status = flightStatus(flight, now); return <div className="hb-countdown"><span>{status.label}</span><strong>{status.value}</strong></div>; }
function FlightCarousel({ flights, edit, remove }: { flights: BookFlight[]; edit: (f: BookFlight) => void; remove: (id: string) => void }) {
  const ref = useRef<HTMLDivElement>(null), [active, setActive] = useState(0);
  const goto = (index: number) => { const node = ref.current?.children[index] as HTMLElement | undefined; if (!node) return; ref.current?.scrollTo({ left: node.offsetLeft - ref.current.offsetLeft, behavior: matchMedia("(prefers-reduced-motion: reduce)").matches ? "instant" : "smooth" }); };
  if (!flights.length) return <Empty icon={<Plane/>}>记录航班或车次后，出发与抵达倒计时会出现在这里。</Empty>;
  return <><div className="hb-flight-carousel" ref={ref} onScroll={() => { const r = ref.current; if (!r) return; const center = r.getBoundingClientRect().left + r.clientWidth / 2; const list = [...r.children]; const nearest = list.reduce((best, node, index) => Math.abs(node.getBoundingClientRect().left + node.clientWidth / 2 - center) < best.distance ? { index, distance: Math.abs(node.getBoundingClientRect().left + node.clientWidth / 2 - center) } : best, { index: 0, distance: Infinity }); setActive(nearest.index); }}>{flights.map(f => <article className="hb-flight" key={f.id}><div className="hb-section-heading"><span className="hb-tag"><Plane size={15}/>{f.number || f.title}</span><div className="hb-actions"><button className="hb-icon" onClick={() => edit(f)} aria-label={`编辑${f.title}`}><Pencil size={16}/></button><button className="hb-icon" onClick={() => remove(f.id)} aria-label={`删除${f.title}`}><Trash2 size={16}/></button></div></div><h3>{f.title}</h3><div className="hb-flight-route"><div><strong>{f.from || "出发地待补充"}</strong><time>{f.departure.replace("T", " ") || "时刻待补充"}</time><small>UTC{f.departureOffset || "待确认"}</small></div><ArrowRight size={24}/><div><strong>{f.to || "抵达地待补充"}</strong><time>{f.arrival.replace("T", " ") || "时刻待补充"}</time><small>UTC{f.arrivalOffset || "待确认"}</small></div></div><FlightClock flight={f}/><p>{f.note}</p>{f.url && <External href={f.url}>承运方 / 预订详情</External>}</article>)}</div><div className="hb-carousel-dots"><button className="hb-icon" aria-label="上一程" disabled={active === 0} onClick={() => goto(active - 1)}><ChevronLeft size={18}/></button>{flights.map((f, i) => <button className={active === i ? "is-active" : ""} key={f.id} aria-label={`查看第 ${i + 1} 程`} aria-current={active === i} onClick={() => goto(i)}/>) }<span>{Math.min(active + 1, flights.length)} / {flights.length}</span><button className="hb-icon" aria-label="下一程" disabled={active >= flights.length - 1} onClick={() => goto(active + 1)}><ChevronRight size={18}/></button></div></>;
}
function RentalClock({ rental: r }: { rental: BookRental }) { const now = useClock(), pickup = instant(r.pickup, r.pickupOffset), end = instant(r.dropoff, r.dropoffOffset); const label = r.returned ? "已还车" : pickup != null && now < pickup ? "距离取车" : end != null && now > end ? "还车时间已过 · 请核对还车状态" : "距离还车"; const target = pickup != null && now < pickup ? pickup : end; return <div className={`hb-countdown${!r.returned && end != null && now >= (pickup || 0) && end - now < 86400000 ? " hb-urgent" : ""}`}><span>{label}</span><strong>{r.returned ? "这一段自驾已收好" : target == null ? "日期或时差待补充" : countdown(target, now)}</strong></div>; }
function Rental({ rental: r, edit, remove, returned }: { rental: BookRental; edit: () => void; remove: () => void; returned: () => void }) {
  const [tab, setTab] = useState<"checklist" | "insurance" | "driving">("checklist");
  return <article className="hb-card"><div className="hb-section-heading"><h3>{r.company} · {r.vehicle || "车型待补充"}</h3><div className="hb-actions"><button className="hb-icon" aria-label={`编辑租车${r.company}`} onClick={edit}><Pencil size={16}/></button><button className="hb-icon" aria-label={`删除租车${r.company}`} onClick={remove}><Trash2 size={16}/></button></div></div><RentalClock rental={r}/><div className="hb-grid"><div><small>取车 · UTC{r.pickupOffset}</small><p>{r.pickup.replace("T", " ") || "时间待补充"}<br/>{r.pickupPlace}</p></div><div><small>还车截止 · UTC{r.dropoffOffset}</small><p>{r.dropoff.replace("T", " ") || "时间待补充"}<br/>{r.returnPlace}</p></div></div><p>{r.price && `费用：${r.price}`}{r.contact && ` · 联系：${r.contact}`}</p><div className="hb-tabs" aria-label="驾驶资料">{(["checklist", "insurance", "driving"] as const).map(t => <button key={t} aria-pressed={tab === t} onClick={() => setTab(t)}>{{ checklist: "取还车检查", insurance: "保险提醒", driving: "驾驶须知" }[t]}</button>)}</div>{r[tab].length ? <ul>{r[tab].map((s, i) => <li key={i}>{s}</li>)}</ul> : <p className="hb-muted">还没有填写，点击编辑添加与你的订单对应的资料。</p>}{tab === "driving" && <div className="hb-actions">{r.links.map((l, i) => <External key={i} href={l.url}>{l.title}</External>)}</div>}<button className="hb-secondary" onClick={returned}>{r.returned ? "撤销已还车" : "我已完成还车"}</button></article>;
}
function DocumentPreview({ doc, onClose }: { doc: BookDocument; onClose: () => void }) {
  const [url, setURL] = useState("");
  useEffect(() => { const raw = atob(doc.data.split(",")[1]); const bytes = Uint8Array.from(raw, c => c.charCodeAt(0)); const objectURL = URL.createObjectURL(new Blob([bytes], { type: doc.type })); setURL(objectURL); return () => URL.revokeObjectURL(objectURL); }, [doc]);
  return <Modal title={doc.name} onClose={onClose}>{url && <><div className="hb-document">{doc.type === "application/pdf" ? <iframe sandbox="" src={url} title={doc.name}/> : <img src={url} alt={doc.name}/>}</div><a className="hb-primary" href={url} download={doc.name}><Download size={17}/>下载原文件</a><p className="hb-muted">若浏览器无法内嵌 PDF，请下载后用系统文件应用查看。</p></>}</Modal>;
}
